# Generated by Django 5.1.4 on 2025-01-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.IntegerField()),
                ('checkin_date', models.DateField()),
                ('is_available', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('updated_at', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=100)),
                ('hotel_name', models.CharField(max_length=200)),
                ('airport_code', models.CharField(max_length=3)),
                ('city_name', models.CharField(max_length=50)),
                ('city_name_ko', models.CharField(max_length=50)),
                ('place_id', models.CharField(max_length=100)),
                ('place_name', models.CharField(max_length=200)),
                ('reviews_score', models.FloatField()),
                ('review_score_word', models.CharField(max_length=50)),
                ('review_nr', models.IntegerField()),
                ('checkin_time', models.CharField(max_length=50)),
                ('checkout_time', models.CharField(max_length=50)),
                ('hotel_class', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance', models.FloatField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
