# Generated by Django 5.1.4 on 2025-01-10 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelsearch',
            old_name='reviews_score',
            new_name='review_score',
        ),
    ]
