# Generated by Django 5.1.4 on 2025-01-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_rename_reviews_score_hotelsearch_review_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelAvailability',
            new_name='hotels_availability',
        ),
        migrations.RenameModel(
            old_name='HotelSearch',
            new_name='hotels_search',
        ),
    ]
