# Generated by Django 5.1.4 on 2025-01-11 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_rename_hotelavailability_hotels_availability_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotels_availability",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="hotels_search",
            options={"managed": False},
        ),
    ]
