# Generated by Django 5.1.4 on 2025-01-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_at', models.TextField()),
                ('departure_date', models.TextField()),
                ('flight_id', models.IntegerField()),
                ('departure_display_code', models.CharField(max_length=10)),
                ('departure_name', models.CharField(max_length=100)),
                ('arrival_display_code', models.CharField(max_length=10)),
                ('arrival_name', models.CharField(max_length=100)),
                ('carrier_names', models.TextField()),
                ('departure_time', models.TextField()),
                ('arrival_time', models.TextField()),
                ('agent_name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('url', models.TextField()),
                ('last_updated', models.TextField()),
                ('stop_count', models.TextField()),
            ],
        ),
    ]
