# Generated by Django 5.1.4 on 2025-01-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='agent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
