# Generated by Django 5.1.4 on 2025-01-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0002_alter_flight_extracted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flight",
            name="id",
        ),
        migrations.AlterField(
            model_name="flight",
            name="extracted_at",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="flight",
            name="flight_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
